---
title: 个人财富管理手册
author: 夏昆
date: '2018-05-09'
slug: 个人财富管理手册
categories:
  - 财富管理
tags:
  - 财富管理
---

## 基本概念
### 生产和消费
-	生产：创造经济价值
-	消费：使用经济价值
-	生产 = 投资 + 消费

###	广义的个人资产负债表
- 资产
    - 人力资本=未来劳务收入的折现
    - 金融资产，私人企业等
- 负债
    - 未来消费支出的折现
    - 金融负债

### 财务风险，满足未来消费的不确定性
-	流动性风险：确保在每个时点有足够的流动资产覆盖当期消费和还债支出
-	资产负债表风险：确保有足够资产覆盖负债

### 复利
- 复合年化收益率→100元投资10年后的财富，1%→110，5%→163，10%→260
- 正复利，做时间的朋友：经济增长，风险溢价，超额收益
-	负复利，做时间的敌人：管理费，交易成本，通胀

## 确立目标
-	财富管理：管理个人资产负债表，规避未来消费得不到满足的风险
-	投资：放弃当前消费（储蓄和投资），满足未来消费

## 制定计划
- 财富管理=管理个人资产负债表
    - 资产端：储蓄和投资
    - 通过资本积累和参与生产，对冲长期消费增长的风险
-	负债端
    - 合理消费，控制物质需求，量入为出
    -	控制金融债务风险
-	消费增长的风险
    - 中国改革开放以来，消费增长长期落后于生产增长（投资驱动的经济）
    - 随着中国向消费型经济转型，消费占比逐渐提高
- 投资流程
    - 布局：资产配置
    - 派兵：选择投资标的/组合
    - 遣将：选择产品/管理人

- 投资风险
    - 风险资产的代表性不足（行业/国家/个股/资本结构等错配的风险
    - 过高的价格买入
    - 灭价值的风险，低效国企等
    - 利益分配的风险
    -	过高的税收
    -	过高的工资支出
    -	高价再融资和其它损害投资者利益的风险

### 风险资产配置（承担市场风险）
- 获得风险回报：大多数时候风险厌恶已经反映在风险资产的价格和预期收益里（无风险无收益，低风险低收益）
- 权益资产配置
    -分享长期经济增长
    -	获得期权价值：投资和风险的不对称性，经济收益是上凸函数，人的适应能力（规避风险/捕捉机会）

### 主要资产类别
1.	人力资产/负债
a.	不可出售
b.	“分红”相对稳定
c.	与经济增长正相关
d.	负债=未来消费的贴现值（衣食住行、娱乐、教育、医疗）
e.	负债与资产增长正相关
2.	现金
a.	短期的安全资产
b.	对冲短期消费缺口的风险（流动性风险）
3.	长期债券
a.	长期的安全资产
b.	对冲长期投资机会下行风险，再投资风险，利率风险（通过锁定长期收益）
4.	股票
a.	长期的安全资产（估值均值回归，时间分散风险，投资周期越长，风险越低）
b.	更高长期收益（如果经济长期增长，获取剩余价值，风险回报）
c.	选择权/上凸性，适应能力（捕捉投资机会和管理风险/成本），尤其在经济萧条期
d.	对冲长期消费上行的风险（通过以合理的价格参与生产力增长）
i.	生产力增长决定消费增长
e.	（有限的）择时提高收益
i.	在价格严重低于价值时更多参与
5.	商品？
a.	工业商品长期跑输通胀（不适合长期持有）
b.	不能对冲经济周期/股/债（收益不相关）
c.	收益主要来源于展期（roll）
d.	期限结构/动量（多空）策略可能有效
6.	其它因素的影响
a.	收入越高，风险资产的配置越高
b.	最低消费水平越高，风险资产的配置越低（相当于负收入）
## 时间维度（投资周期）
•	短期持有现金对冲流动性风险
•	长期持有债券对冲消费下行风险（经济衰退风险，利率风险，再投资风险）
•	长期持有股票对冲消费上行风险（通过以合理的价格参与生产增长）
•	投资周期越长，股票风险越低好于债券 （股票估值均值回归，而利率呈现均值偏离）
   
# 证券选择
分散与集中
•	如果有比较优势就集中，否则分散
•	大容量长期战胜市场难度很大
o	长期来看，市场基本有效
o	证券选择和产品选择不容易形成护城河
o	容量有限：深度和宽度的矛盾
超额收益的来源
•	价格偏离预期价值 （预期现金流折现），供求关系变化
o	流动性变化（杠杆，资产轮动）
o	风险偏好的变化（贪婪、恐惧）
o	供应变化（稀缺性，IPO，再融资）
•	预期价值偏离实际价值
o	信息优势
o	投资逻辑的差异
	


